"""
Django settings for django_Qw_Project project.

Generated by 'django-admin startproject' using Django 4.2.21.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import sys
from pathlib import Path
from decouple import config


# 定义知识库文件的存放路径
BASE_DIR = Path(__file__).resolve().parent.parent
# BASE_DIR 是项目根目录，os.path.join 会把它拼成完整路径
KNOWLEDGE_BASE_DIR = os.path.join(BASE_DIR, 'knowledge_base')

# 确保这个文件夹存在，如果不存在就自动创建
if not os.path.exists(KNOWLEDGE_BASE_DIR):
    os.makedirs(KNOWLEDGE_BASE_DIR)



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-zwil7w#msj66(r*51uft*-+-w&!f5ialah6(f*w2j&d#lu9h&+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app01.apps.App01Config',
    'documents.apps.DocumentsConfig',
    'chat.apps.ChatConfig',
    'rest_framework',
    'drf_spectacular',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# DRF 全局配置
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_RENDERER_CLASSES': ['rest_framework.renderers.JSONRenderer'],  # 禁用浏览器表单渲染，纯API模式
}

# 临时开发跨域配置（上线前再收紧）
CORS_ALLOW_ALL_ORIGINS = True



ROOT_URLCONF = 'django_Qw_Project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_Qw_Project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': config('DB_HOST', default='db'),        # Docker 里服务名叫 db
        'PORT': config('DB_PORT', default='5432'),
        'NAME': config('DB_NAME', default='postgres'), # 改成你 docker-compose 里的库名
        'USER': config('DB_USER', default='user'),
        'PASSWORD': config('DB_PASSWORD', default='zc20040714 '),
    }
}

# redis配置
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://redis:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'






# 硅基流动 LLM 配置
LLM_CONFIG = {
    # 使用我们刚才写的兼容 OpenAI 格式的原生 Provider
    "provider": "openai_compatible",

    # 你的硅基流动 API Key (以 sk- 开头)
    "api_key": config("SILICONFLOW_API_KEY", default="sk-omccqrcyezewodecrrwhficgclmaohdphfiefncnluvkufqk"),

    # 硅基流动的官方 Base URL (注意结尾不要带 /v1，我们的代码里会自动拼)
    "base_url": "https://api.siliconflow.cn",

    # 你在硅基流动上选用的模型 ID，比如 DeepSeek-V3 或 Qwen2.5
    "model": "deepseek-ai/DeepSeek-V3",

    # 生成参数
    "temperature": 0.7,
    "max_tokens": 2048,
}
